
# where to find the sample sheet - assume we are in the parent folder (not workflow)
sample_sheet: "config/sample_sheet.csv"

# rule execution list 
# this goes into the get_rules function laid out in the common.smk file

FASTP: False
FASTQC: False
NONPAREIL: False
ASSEMBLY: False
ASSEMBLY_QC: False
ASSEMBLY_PARSE: True
BIN: False
BIN_QC: True
TAXONOMY: True